api:
  port: 3000
  logFormat: 'tiny'
logLevel: 'debug'
database:
  user: WeatherTrack
  host: localhost
  database: WeatherTrack
  password: mysecretpassword
  port: 5432
  max: 50
  idleTimeoutMillis: 60000 
  connectionTimeoutMillis: 5000 