api:
  port: 80
  logFormat: 'tiny'
logLevel: 'info'
database:
  user: ${DB_USER}
  host: ${DB_HOST}
  database: ${DB_NAME}
  password: ${DB_PASSWORD}
  port: ${DB_PORT}
  max: ${DB_MAX_CONNECTIONS}
  idleTimeoutMillis: ${DB_IDLE_TIMEOUT}
  connectionTimeoutMillis: ${DB_CONN_TIMEOUT}